"""refactor models

Revision ID: 2968871e6c28
Revises: ec55d8b21c6d
Create Date: 2026-05-11 09:21:01.276419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2968871e6c28'
down_revision: Union[str, Sequence[str], None] = 'ec55d8b21c6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE mod_requests ALTER COLUMN status DROP DEFAULT")
    op.execute("ALTER TABLE mod_requests ALTER COLUMN status TYPE applicationstatus USING status::applicationstatus")
    op.execute("ALTER TABLE mod_requests ALTER COLUMN status SET DEFAULT 'pending'")
    op.add_column('users', sa.Column('username', sa.String(), nullable=True))
    op.execute("UPDATE users SET username = email WHERE username IS NULL")
    op.alter_column('users', 'username', nullable=False)
    op.drop_constraint(op.f('users_name_key'), 'users', type_='unique')
    op.drop_constraint(op.f('users_phone_key'), 'users', type_='unique')
    op.create_index('ix_user_username', 'users', ['username'], unique=False, postgresql_using='hash')
    op.create_unique_constraint(None, 'users', ['username'])
    op.drop_column('users', 'phone')
    op.drop_column('users', 'name')
    op.add_column('orderitems', sa.Column('product_name', sa.String(), nullable=False))
    op.add_column('orderitems', sa.Column('shop_product_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('orderitems_product_id_fkey'), 'orderitems', type_='foreignkey')
    op.create_foreign_key(None, 'orderitems', 'products', ['product_name'], ['name'])
    op.create_foreign_key(None, 'orderitems', 'shopproducts', ['shop_product_id'], ['id'])
    op.drop_column('orderitems', 'product_id')
    op.add_column('orders', sa.Column('owner_name', sa.String(), nullable=False))
    op.drop_constraint(op.f('orders_user_id_fkey'), 'orders', type_='foreignkey')
    op.create_foreign_key(None, 'orders', 'users', ['owner_name'], ['username'])
    op.drop_column('orders', 'user_id')
    op.add_column('products', sa.Column('category', sa.String(), nullable=False))
    op.create_index('ix_product_name', 'products', ['name'], unique=False, postgresql_using='hash')
    op.drop_constraint(op.f('products_category_id_fkey'), 'products', type_='foreignkey')
    op.create_foreign_key(None, 'products', 'categories', ['category'], ['name'])
    op.drop_column('products', 'price')
    op.drop_column('products', 'category_id')
    op.drop_column('products', 'quantity')
    op.alter_column('sellerapplications', 'text',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index('ix_shop_name', 'shops', ['name'], unique=False, postgresql_using='hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_index('ix_user_username', table_name='users', postgresql_using='hash')
    op.create_unique_constraint(op.f('users_phone_key'), 'users', ['phone'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('users_name_key'), 'users', ['name'], postgresql_nulls_not_distinct=False)
    op.drop_column('users', 'username')
    op.drop_index('ix_shop_name', table_name='shops', postgresql_using='hash')
    op.alter_column('sellerapplications', 'text',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('products', sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('products', sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('price', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.create_foreign_key(op.f('products_category_id_fkey'), 'products', 'categories', ['category_id'], ['id'])
    op.drop_index('ix_product_name', table_name='products', postgresql_using='hash')
    op.drop_column('products', 'category')
    op.add_column('orders', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.create_foreign_key(op.f('orders_user_id_fkey'), 'orders', 'users', ['user_id'], ['id'])
    op.drop_column('orders', 'owner_name')
    op.add_column('orderitems', sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'orderitems', type_='foreignkey')
    op.drop_constraint(None, 'orderitems', type_='foreignkey')
    op.create_foreign_key(op.f('orderitems_product_id_fkey'), 'orderitems', 'products', ['product_id'], ['id'])
    op.drop_column('orderitems', 'shop_product_id')
    op.drop_column('orderitems', 'product_name')
    op.alter_column('mod_requests', 'status',
               existing_type=sa.Enum('pending', 'approved', 'rejected', name='applicationstatus'),
               type_=sa.VARCHAR(),
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    # ### end Alembic commands ###
