"""add shop_id to orders

Revision ID: d3a7a9fe34bb
Revises: b462195a6878
Create Date: 2026-06-03 11:24:38.658725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3a7a9fe34bb'
down_revision: Union[str, Sequence[str], None] = 'b462195a6878'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('shop_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'orders', 'shops', ['shop_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'shop_id')
    # ### end Alembic commands ###
