"""add ModerationRequest

Revision ID: ec55d8b21c6d
Revises: b4602232a3ae
Create Date: 2026-04-29 14:26:06.876024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec55d8b21c6d'
down_revision: Union[str, Sequence[str], None] = 'b4602232a3ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("""
        CREATE TABLE mod_requests (
            id SERIAL PRIMARY KEY,
            action_type actiontype NOT NULL,
            status applicationstatus NOT NULL DEFAULT 'pending',
            entity_id INTEGER NOT NULL,
            created_at TIMESTAMP DEFAULT now() NOT NULL,
            shop_id INTEGER NOT NULL REFERENCES shops(id),
            reviewed_by INTEGER REFERENCES users(id)
        );
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mod_requests')
    # ### end Alembic commands ###
